version: '3'

services:
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/certs:/etc/nginx/certs
  nginx:
    image: nginx
    volumes:
      - ./src/laravel:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
#      - ./docker/nginx/php.conf:/etc/nginx/conf.d/php.conf
    depends_on:
      - php
    environment:
      - VIRTUAL_HOST=local-dev.noir.ai
      - CERT_NAME=default
    restart: always
  php:
    build: ./docker/php
    volumes:
      - ./src/laravel:/app
    environment:
      - TZ=Asia/Tokyo
    expose:
      - 9000
  node:
    build: ./docker/node
    ports:
      - "3000:3000"
    volumes:
      - ./src/nuxtjs:/app:cached
    tty: true
    stdin_open: true
  mysql:
    image: mysql:8.0
    platform: linux/x86_64
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - TZ='Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"